### ISSUE TITLE
vim-fetlang: Language support for Fetlang

### ISSUE THREAD

**Issue by kutsan** [Property404/fetlang#21]
https://github.com/kutsan/vim-fetlang

I have been developing language support for vim and you can check out by the link above. It's still very beginning of its development. Only wrote initial syntax support (for keywords and comments), which works okay. I couldn't find another project for it, it's probably the first one. I will try to cover syntax, indent, compiler and sections support. Most things don't work for now. I have been still learning the Fetlang itself, so, I'll make it more mature by the time of progress while I am free.

Since this one is not a real issue. Feel free to close it if you wish.

**Comment by Property404** [comment]
This is great! I was actually thinking of making something like this, but I was lazy. I'll have to look more at this later

**Comment by kutsan** [comment]
You're welcome! I am very glad about that.

Also, I have two questions. I know it's out of topic but.

First one, will you improve numbers for Fetlang in future?

> Fraction literals are represented by words.

I mean, this is fun but in reality it's really annoying to write like that. I find myself occasionally at a very frustrating situation when dealing with problems. I still don't know if this language intended to be a real one or just a meme language.

```fetlang
lick Duke's left nipple 20 times
```

Why we can't write like this?

Second one is, is there any such feature like JavaScript's objects? How can we map a key to a value?

```fetlang
lick Kutsan's left arm three times
lick Kutsan's right leg two times

make slave scream Kutsan's left arm
make slave scream Kutsan's right leg
```

When writing something like this, I think they should be separate values. Kutsan should be an object and it should contain something like this `{ "left arm": three, "right leg": two }`. So, when we making the slave scream, she should print out 3 for left arm and 5 for right leg.

**Comment by Property404** [comment]
The way you write numbers in Fetlang is sort of intentionally obnoxious. It is an esolang, after all.  

That behaviour is also intentional. Possessives are just sugar for making your programs look more erotic. It gives the programmer/eroticist more leeway.

**Comment by kutsan** [comment]
But if you do that with the way I said, it won't be leeway and its eroticness will still persist. Don't you think so?

**Comment by Property404** [comment]
On topic - when your vim plugin gets a bit more complete, could I incorporate (a possibly modified version of) it into the Fetlang repo? (I don't think the GPL conflicts with Fetlang's permissive license because it's a separate piece of code, and I'm not linking to it in any way, but I feel it's safer to ask)

**Comment by Property404** [comment]
Part of the point of possessives is to be able to talk about the same value in many different ways, so you don't get too repetitive

**Comment by kutsan** [comment]
> could I incorporate

Sure, as long as it stay free for everyone, I don't mind anything; copying or linking. You can fork it too. That's my default license but I can change it to MIT if you think they won't work out together.

**Comment by Property404** [comment]
Thanks - I don't think you need to change it to MIT, but I'll ask my lawyers :P

**Comment by kutsan** [comment]
Could you please check out the current state of the plugin? I think syntax support is done. I also wrote compiler support and optional run plugin. Can you check out those too?

**Comment by Property404** [comment]
Sure, next time I have wifi access
