### ISSUE TITLE
More Appropriate Syntax?

### ISSUE THREAD

**Issue by Maxzilla60** [Property404/fetlang#9]
I wanna start out saying this is a hilarious idea and I'm impressed you've taken the time to flesh it out! :smiley: 

What I have is a suggestion. You say the language
>is designed such that the source code looks like poorly written fetish erotica.

The implementation currently uses imperative sentences:

```
Make Sean moan
Have Amy hogtie Sean
Make Slave scream Sean's name
```

I feel it would be more appropriate to use declarative sentences. This way the code looks a lot more like an actual story:

```
Sean moans
Amy hogties Sean
Slave screams Sean's name
```

I completely understand that this would require a big rewrite of the repo. It's an idea. :grin:

**Comment by NoelAbrahams** [comment]
+1 I found it quite hard to reach a climax with the existing syntax.

**Comment by ThePilgrim** [comment]
I like this idea, I still have problems halting with the current syntax

**Comment by Property404** [comment]
Maybe, but it's more work :P
